# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f9f09dab19e927b9b49b94f99df665cd20fbc152f36bbfd9bbced6708c66d6a8a54f3008fb9c0c858a387d6579cd6a331e3a028dac2ed5d6d8da51b1ff8acfa
  host: http://192.168.1.10:3000

test:
  secret_key_base: 1cf9015c8beb0f2c8cce9a2cdac90be56df087f509682b5f515fdc87ccb26a02cac7e5888e28ed27f9d1d27971ff1a7f20b0cad8f3fd50b84743836bb810a996

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 1cf9015c8beb0f2c8cce9a2cdac90be56df087f509682b5f515fdc87ccb26a02cac7e5888e28ed27f9d1d27971ff1a7f20b0cad8f3fd50b84743836bb810a996
  host: http://new-app-for-api.herokuapp.com
  mandrill_api_key: <%= ENV["MANDRILL_API_KEY"] %>
